[functions]
  external_node_modules = ["express", "@notionhq/client", "cors", "axios"]
  node_bundler = "esbuild"

[build]
  functions = "functions"

[dev]
  publish = "dist"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"