POST https://id.twitch.tv/oauth2/token?client_id=m83mbo6r56trenidw05tz7rl0qake9&client_secret=n2ch9j40yxz8rrun8ig90g8dw7m5o7&grant_type=client_credentials



# POST https://api.igdb.com/v4/games
# Client-ID: m83mbo6r56trenidw05tz7rl0qake9
# Authorization: Bearer 822uqjae0jq5qanlv684fx6w8fuseh
# fields: artworks


